name: Deploy to S3 CDN

on:
  workflow_dispatch:
    inputs:
      ref:
        required: false
        description: branch or tag name
        default: ""
      version:
        required: true
        description: version to identify release with

permissions:
  contents: read
  packages: read

jobs:
  build-react-app:
    name: Build React App for CDN
    runs-on: ubuntu-latest

    steps:
      - name: Print deployer name
        run: echo "deployer is ${{ github.actor }}"

      - name: Check if base branch is main
        id: check-base-branch
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed("The workflow has to be triggered from main branch")

      - name: Check if authorized to run this workflow
        id: check-actor
        if: ${{ !contains(vars.AUTHORIZED_USERS, github.actor) }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed("You're not authorized to run this workflow, please contact raja@growfin.ai")

      - name: Check out branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install Node Modules
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-build-cdn
          path: dist

  publish-to-S3:
    name: Deploy CDN assets to S3
    runs-on: ubuntu-latest
    needs: ["build-react-app"]

    steps:
      - name: Get build files
        uses: actions/download-artifact@v4
        with:
          name: react-build-cdn
          path: dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload CDN files to S3
        run: |
          # Set S3 path prefix (empty string for root, or folder name)
          S3_PREFIX="${{ secrets.S3_PATH_PREFIX }}"
          if [ -n "$S3_PREFIX" ]; then
            S3_PREFIX="${S3_PREFIX}/"
          fi

          # Upload CSS file with cache headers (15 days)
          aws s3 cp dist/style.css s3://${{ secrets.S3_BUCKET_NAME }}/${S3_PREFIX}style.css --acl public-read --content-type "text/css" --cache-control "public, max-age=1296000"

          # Upload JS file with cache headers (15 days)
          aws s3 cp dist/script.js s3://${{ secrets.S3_BUCKET_NAME }}/${S3_PREFIX}script.js --acl public-read --content-type "application/javascript" --cache-control "public, max-age=1296000"

          echo "Files uploaded successfully!"
          echo "CSS URL: https://${{ secrets.S3_BUCKET_NAME }}.s3.${{ secrets.AWS_REGION }}.amazonaws.com/${S3_PREFIX}style.css"
          echo "JS URL: https://${{ secrets.S3_BUCKET_NAME }}.s3.${{ secrets.AWS_REGION }}.amazonaws.com/${S3_PREFIX}script.js"

      - name: Clear CDN cache
        if: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID != '' }}
        run: |
          # Set S3 path prefix for CloudFront invalidation
          S3_PREFIX="${{ secrets.S3_PATH_PREFIX }}"
          if [ -n "$S3_PREFIX" ]; then
            INVALIDATION_PATH="/${S3_PREFIX}/*"
          else
            INVALIDATION_PATH="/*"
          fi

          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "$INVALIDATION_PATH"
